name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://test:test@localhost:5432/testdb
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: debug pastas
        run: ls -R
        
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependências
        working-directory: backend/post-service      
        run: npm install

      - name: Gerar cliente Prisma
        working-directory: backend/post-service
        run: npx prisma generate

      - name: Executar migrações do Prisma
        working-directory: backend/post-service
        run: npx prisma migrate deploy

      - name: Build do TypeScript
        working-directory: backend/post-service
        run: npm run build

      - name: Testes
        working-directory: backend/post-service
        run: npm test