name: Deploy Supabase 

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Supabase CLI
        run: npm install -g supabase

      - name: Deploy functions
        run: supabase functions deploy posts --project-ref $PROJECT_REF
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}